# Generated by Django 4.2.7 on 2023-12-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Event_Booking_System',
            },
        ),
    ]
